name: "Salesforce CI/CD Pipeline"
on:
  workflow_dispatch: # Allows manual triggering of the workflow from the GitHub Actions tab along with variable inputs

  push:
    branches:
      - main
      - feature/** # Reason for double asterisk: to include all subdirectories under feature for eg feautre/abc as well as feature/abc/def


      
jobs:
  deploy:
    
    # This condition ensures that the deploy job runs for both push and workflow_dispatch events, allowing for flexibility in how the pipeline is triggered. It checks if the event is either a push or a manual trigger, ensuring that the deployment process can be initiated in both scenarios. Also it checks if the branch is main, uat, qa or int, ensuring that deployments are only triggered for these specific branches, preventing this job to run when code is pushed to other branches like feature branches. This helps in maintaining a controlled deployment process, where only changes from specific branches are deployed to the respective environments, reducing the risk of unintended deployments and ensuring that the deployment process is aligned with the branching strategy of the project.
    if: ${{ (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && (github.ref_name == 'main' || github.ref_name == 'uat' || github.ref_name == 'qa' || github.ref_name == 'int') }} 
    
    # The use of 'ubuntu-latest' as the runner provides a stable and widely used environment for running the CI/CD pipeline, ensuring compatibility with a wide range of tools and dependencies commonly used in Salesforce development and deployment processes. It also allows for easy maintenance and updates, as GitHub regularly updates the 'ubuntu-latest' image with the latest security patches and software versions.
    runs-on: ubuntu-latest
    
    # Set the environment based on the branch name. This allows for environment-specific configurations and deployments, ensuring that changes are deployed to the correct environment based on the branch being pushed or manually triggered. The use of logical OR (||) ensures that the correct environment is selected based on the branch name, providing a clear mapping between branches and their corresponding environments.
    # You might be thinking when i manually run the workflow from the GitHub Actions tab, there is no push-to-branch associated with it, so how will this condition work? Well it does have since you need to select the branch while triggering the workflow manually, so it will take the branch name you select and set the environment accordingly. For example, if you select main branch while triggering the workflow manually, it will set the environment to production.
    environment: ${{ (github.ref_name == 'main' && 'production') || (github.ref_name == 'uat' && 'uat') || (github.ref_name == 'qa' && 'qa') || (github.ref_name == 'int' && 'int') }}                  
    
    steps:
       # Checkout the code 
       - name: "Checkout code"
         uses: actions/checkout@v6
         with:
           fetch-depth: 0 # Fetch all history for all branches and tags

       # Just quickly check the values of
       - name: "Print values of currently checked out branch and event details"
         run: |
           echo "Branch/Ref Name: ${{ github.ref_name }}"  # This gives for eg main, uat, feature/abc etc. without refs/heads/ prefix
           echo "Event Name: ${{ github.event_name }}"     # This gives the event that triggered the workflow, for eg push, workflow_dispatch etc.
           echo "Ref: ${{ github.ref }}"                   # This gives the full ref that triggered the workflow, for eg refs/heads/main, refs/heads/uat, refs/heads/feature/abc etc. It includes the refs/heads/ prefix which indicates that it's a branch reference.
          
           # VIMP:The cirrent checkout branch is determined by the ref that triggered the workflow. So if the workflow was triggered by a push to main branch, then main branch will be checked out. If it was triggered by a push to feature/abc branch, then feature/abc branch will be checked out onto the latest commit of that branch. If it was triggered manually and you select main branch while triggering, then main branch will be checked out.
           echo "VIMP:The cirrent checkout branch is determined by the ref that triggered the workflow. So if the workflow was triggered by a push to main branch, then main branch will be checked out. If it was triggered by a push to feature/abc branch, then feature/abc branch will be checked out onto the latest commit of that branch. If it was triggered manually and you select main branch while triggering, then main branch will be checked out."
           git branch                                      # This will show the currently checked out branch with an asterisk (*) next to it. For example, if main branch is checked out, it will show * main. 
           

       # Install salesforce cli    
       - name: "Install Salesforce CLI"
         run: |
           npm install @salesforce/cli --global
           which sf
           command -v sf
           pwd

      # Verify Salesforce CLI installation     
       - name: "Check if Salesforce CLI is working"
         run: |
           if sf --version | grep "/" ; then
             echo "Salesforce CLI is installed and working."
           else
             echo "Salesforce CLI installation failed."
             exit 1
           fi
      
      # Create jwt key file from the content stored in GitHub secrets
       - name: "Create JWT Key File"
         run: |
           echo "${{ secrets.JWT_KEY_FILE_CONTENT }}" > server.key 
           # Set appropriate permissions for the key file i.e. RW for owner only
           chmod 600 server.key 


     # Verify that the JWT key file has been created successfully and has the correct permissions. This step is crucial to ensure that the authentication process can proceed without issues, as an improperly created key file can lead to authentication failures.
       - name: "Verify JWT Key File Creation"
         run: |
           if [ -f server.key ]; then
             echo "JWT key file created successfully."
             ls -l server.key # This will show the permissions of the file, which should be -rw------- (600) for security reasons.
           else
             echo "Failed to create JWT key file."
             exit 1
           fi      

      # Authenticate to Salesforce org using JWT-based flow
       - name: "Authenticate to Salesforce Org"
         run: |
           sf org login jwt --client-id ${{ secrets.CLIENT_ID }} --jwt-key-file server.key --username ${{ vars.USERNAME }} --set-default --instance-url ${{ vars.INSTANCE_URL }}


      # Verify authentication by displaying the authenticated org's username
       - name: "Verify Authentication"
         run: |
           sf org list     

        
      # Cean up the JWT key file at last. This will ensure that the key file is not left on the runner after the workflow completes, enhancing security by minimizing the risk of unauthorized access to the key file.
       - name: "Clean Up JWT Key File"
         if: always() # This ensures that the cleanup step runs regardless of the success or failure of previous steps, ensuring that the key file is removed in all scenarios.
         run: |
           # Remove the JWT key file to prevent unauthorized access -f flag is used to force deletion without prompting for confirmation, which is useful in automated scripts to ensure that the cleanup process is not interrupted.
           rm -f server.key     

           # verify that the key file has been removed successfully
           # [ ... ] this is test command to check if the file exists. -f seraches for file only in the current directory and returns true if the file exists and is a regular file. 
           # CONT.. Other options are -d for directory, -e for existence (file or directory), etc. In this case, we want to check if the file still exists after attempting to remove it, 
           # CONT.. which would indicate a failure in the cleanup process.
           # Reason for using this [] over ls | grep is that the latter can be less reliable in scripts, especially if there are multiple files or if the file name contains spaces or special characters. The test command with -f provides a more direct and reliable way to check for the existence of a specific file.
           
           if [ -f server.key ]; then 
             echo "Failed to remove the JWT key file."
             exit 1 # Exit with a non-zero status to indicate failure, which can be useful for debugging and ensuring that the workflow does not proceed if the cleanup step fails.
           else
             echo "JWT key file removed successfully."
           fi
